### ISSUE TITLE
Rename Branch iroha2 to iroha2-stable

### ISSUE THREAD

**Issue by astrokov7** [hyperledger/iroha-2-docs#115]
The branch is iroha2 no longer exists. Now iroha2-stable is used instead. We need to rename wherever iroha2 branch is mentioned. For example here https://hyperledger.github.io/iroha-2-docs/guide/build-and-install.html#install-iroha-from-github .

**Comment by outoftardis** [comment]
The branch is being renamed back to `iroha` so I'll close this issue as not relevant anymore

**Comment by appetrosyan** [comment]
The branch stays as Iroha-stable, the renaming must be carried out.
