### ISSUE TITLE
Add mention of iroha-javascript repository in JS guide.

### ISSUE THREAD

**Issue by astrokov7** [hyperledger/iroha-2-docs#129]
We need to mention ours done repository of JS project which customers will do to clone and use from the box.
`git clone https://github.com/hyperledger/iroha-javascript.git --branch iroha2`

**Comment by outoftardis** [comment]
Hm, is it enough to only provide this info? I.e. wouldn't some other instructions change as well?

**Comment by 6r1d** [comment]
> Hm, is it enough to only provide this info? I.e. wouldn't some other instructions change as well if you are using the repo instead of published packages?

From our dialog with Alex, I suppose some additional details may be mentioned:

* The active development happens here
* Issues may contain solutions and hints for someone debugging the code that is using `iroha-javascript`
* The code here would be more fresh and less stable than the published packages.

I am not sure how useful this is, though. Probably it is, to some extent. :-)

**Comment by 6r1d** [comment]
...And Alex just mentioned that the JS app demo is located [here](https://github.com/hyperledger/iroha-javascript/tree/iroha2/packages/client/test/integration/test-web). This certainly sounds useful for someone working on the frontend.

**Comment by outoftardis** [comment]
@6r1d thanks I've added some of this info

> Plus, @astrokov7 just mentioned that the JS app demo is located [here](https://github.com/hyperledger/iroha-javascript/tree/iroha2/packages/client/test/integration/test-web). This certainly sounds useful for someone working on the frontend.

I'm not sure about this, this doesn't look like a demo -- maybe I don't understand something, but these are just tests. If it's really is a demo, we might need to mention this in the repository itself.
