### ISSUE TITLE
Fix phrasing on the WASM page

### ISSUE THREAD

**Issue by outoftardis** [hyperledger/iroha-2-docs#162]
![image](https://user-images.githubusercontent.com/17865025/189399770-7ee7653f-fc72-4172-9458-ed59dfad9a34.png)

https://hyperledger.github.io/iroha-2-docs/guide/advanced/wasm.html

I don't really know what this is supposed to mean, @appetrosyan can you help? Not sure if this is something I overlooked when I was reviewing this chapter, or if it's the result of the commit history mixup we had recently.

**Comment by WRRicht3r** [comment]
From the context of the paragraph and the sentence, I think it could be something like 
"While simple ISI smart contracts are compact (usually a few bytes), they need different kinds to be manually optimised."
