### ISSUE TITLE
Add more information on Triggers Page

### ISSUE THREAD

**Issue by astrokov7** [hyperledger/iroha-2-docs#191]
Add more information on Triggers Page
![image.png](https://images.zenhubusercontent.com/62ff7ff6035024b7529178f9/9c8e23e1-9210-46bb-accd-a723c73eff03)

**Comment by outoftardis** [comment]
the link works for me, it leads to this part of the page: https://hyperledger.github.io/iroha-2-docs/guide/advanced/triggers.html#supported-isi
