### ISSUE TITLE
Update the Iroha Special Instructions page

### ISSUE THREAD

**Issue by astrokov7** [hyperledger/iroha-2-docs#193]
![image.png](https://images.zenhubusercontent.com/62ff7ff6035024b7529178f9/3bdfa7a3-f30b-43df-b0df-0d72048913b2)

![image.png](https://images.zenhubusercontent.com/62ff7ff6035024b7529178f9/f287562f-0931-4ebf-8f7a-5748dffbf9d0)

![image.png](https://images.zenhubusercontent.com/62ff7ff6035024b7529178f9/297ca3f0-848e-41fd-89da-e5b003246afe)

![image.png](https://images.zenhubusercontent.com/62ff7ff6035024b7529178f9/3799d336-102a-4e19-9331-ffea6fd6cbb1)

![image.png](https://images.zenhubusercontent.com/62ff7ff6035024b7529178f9/0c113664-106b-407c-9dbb-605aecb064e4)

![image.png](https://images.zenhubusercontent.com/62ff7ff6035024b7529178f9/c6565106-7891-4f64-9faa-a7d72f529dba)

**Comment by outoftardis** [comment]
Fixed broken links in #185

**Comment by outoftardis** [comment]
addressed in #200
