### ISSUE TITLE
I can't solve permition iroha2 tutorial 

### ISSUE THREAD

**Issue by akiomax** [hyperledger/iroha-2-docs#226]
root@localhost:/usr/local/src/iroha/test_docker# ./iroha_client_cli account grant --id "mad_hatter@looking_glass" --permission permission_token.json
error: Invalid value "permission_token.json" for '--permission <PERMISSION>': Failed to deserialize the permission token from file permission_token.json

root@localhost:/usr/local/src/iroha/test_docker# cat permission_token.json
{"definition_id":"can_transfer_user_assets","params":{"asset_id":{"Id":{"AssetId":"tea#looking_glass"}},"account_id":{"Id":{"AccountId":"mad_hatter@looking_glass"}}}}

Command out put 
[
    Asset {
        id: Id {
            definition_id: DefinitionId {
                name: "tea",
                domain_id: Id {
                    name: "looking_glass",
                },
            },
            account_id: Id {
                name: "mad_hatter",
                domain_id: Id {
                    name: "looking_glass",
                },
            },
        },
        value: Quantity(
            2300,
        ),
    },
    Asset {
        id: Id {
            definition_id: DefinitionId {
                name: "cabbage",
                domain_id: Id {
                    name: "garden_of_live_flowers",
                },
            },
            account_id: Id {
                name: "alice",
                domain_id: Id {
                    name: "wonderland",
                },
            },
        },
        value: Quantity(
            44,
        ),
    },
    Asset {
        id: Id {
            definition_id: DefinitionId {
                name: "rose",
                domain_id: Id {
                    name: "wonderland",
                },
            },
            account_id: Id {
                name: "alice",
                domain_id: Id {
                    name: "wonderland",
                },
            },
        },
        value: Quantity(
            13,
        ),
    },
]

**Comment by ilchu** [comment]
Hello! Our tutorial is still a work in progress, so it is not completely up to date yet. Asset ids are made of account id **and** asset definition id. That is, both these fields should be specified for it to parse properly.

There is a shorthand notation to specify both of these ids in a single string. It could either be `"asset_name#asset_domain#account_name@account_domain"`, or an even shorter version when asset's domain and account's domain are equal, as it is in your case: `"asset_name##account_name@account_domain"`.

So most ergonomically `permission.json` only needs to contain this:
```json
{
  "definition_id": "can_transfer_user_assets",
  "params": {
    "asset_id": {
      "Id": {
        "AssetId": "tea##mad_hatter@looking_glass"
      }
    }
  }
}

```
