### ISSUE TITLE
Documentation structure

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#252]
I've received a lot of requests regarding the Iroha 1 support. When I ask people why they are interested in an older version, I often hear about the documentation: so far, when someone starts reading it, they see these sections: "`Getting started`" → "`How Iroha works`", "`Iroha 2 vs Iroha 1`", "**`Build and Install Iroha 2`**". Not everyone is ready to build the code in a language they may not know.

**That minor confusion pushes away people who are new here because they feel like Iroha 2 needs to be completed, so they look at version 1 instead. They tend to read the documentation first, and immediately ask about Iroha 1 in community without even mentioning Iroha v2.**

Yes, we have the "`Bring up a minimal network`" section, but I don't think it should be at the same article and a different name would help as well. While we're used to this structure, newbies may not know Rust, so they see a number of packages to install and build at the very start and get confused.
What they need is some other way to quickly try Iroha 2 to see its advantages and disadvantages. Docker would be one way here; Nix packages in the future would help a lot.

*As a small note, Kubernetes has a [playground](https://labs.play-with-k8s.com/) with a web terminal and stable build installed. You log in, try the actual build and you understand how it works. GIT [had a page](https://github.blog/2012-07-04-try-git-in-your-browser/) on GitHub where you can type commands and see what you get, although without a VM. It's not something we can try immediately, but I'll leave it there as a note on good practices. At some point, we may add a small open-source demo on Python or JS displaying Iroha 2 running and exchanging the several token types, but I'd like to hear other opinions.*

A **current solution** would be to reorganize the docs to point out how to use Docker above everything else.

**Comment by baziorek** [comment]
I'd like to add another idea - why not to add information that Iroha 2 should be used instead in documentation of Iroha 1:
https://iroha.readthedocs.io/en/develop/getting_started/index.html

**Comment by 6r1d** [comment]
Thank you, @baziorek! Actually, https://github.com/hyperledger/iroha/pull/3071 may be quite close to what you describe. The only problem here is that the documentation builds are still not repaired and Read the Docs seems to have a peculiar situation with its dependencies I am addressing.

**Comment by outoftardis** [comment]
> A current solution would be to reorganize the docs to point out how to use Docker above everything else.

That makes sense
