### ISSUE TITLE
Document current compose configuration and the motivation behind it

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#255]
Periodically, people ask me how and why the Compose is configured in the way it is.

While it'll be partially a copy of the Compose doc, in another part, it'll explain:

* Why exactly do we have four nodes in our primary example (`3f+1` thresholds)
* How many physical or virtual servers are necessary for Iroha configuration?
* How to connect the peers in Docker-compose config and outside of it?
* Where the config files are located
* Why they are essential for Iroha
* What Iroha is accessing on the disk while loading and in which order

This would allow people who don't know Iroha as well to understand it better and make their configurations.
On the downside, we'll have to update the doc when we change these files and our Docker-compose configuration.

**Comment by 6r1d** [comment]
These are being updated with Kagami and checked with CI.
I should return to this issue and ask Dmitry about it.

**Comment by 0x009922** [comment]
Currently `docker-compose.dev.*.yml` files are generated by ~~Kagami~~ `iroha_swarm`:

- https://github.com/hyperledger/iroha/issues/3648
- https://github.com/hyperledger/iroha/pull/3669

However, there is an issue:

- https://github.com/hyperledger/iroha/issues/3889
