### ISSUE TITLE
Maximum field lengths

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#256]
@astrokov7 just asked about the maximum length available for a `domain` / `account` / `asset` name.
He thinks it'll match the maximum length for the data type, which I believe is something to specify in the docs.

**Comment by 6r1d** [comment]
The maximum number of characters, including UTF-8 ones here, is currently limited by two factors, `[0, u32::MAX]` and the stack space that is currently allocated.

We want to limit names further so the users don't pick unreasonable lengths for those and blockchains don't desync.
This parameter will be set through an ISI. We have agreed on an amount of `256` characters, something with this maximum size:

`cbbcddbce_dcecde_dec_ecbb_ddddaedabcdded_da_dd___e_bbd_debcabebdbeaebcaabdca_eeeba_a_ddceeaedeb_ecad_cbceebddd_b_ebdecb_d_aa_a_bbc_eaceece_eae_edb__ecadacae_cdaeace_ede_aeadad__cbbc_ac_ee_ae_cdbbe_e__cbedc__ebdaed__abaaed_ebbba_ccebbceaa_ed_abedeeacddeaeae`

Later, we'll also restrict the symbols being used in the names:

- Whitespaces will be excluded because most people can’t visually distinguish a non-breaking space from a space or four spaces from a tab.
-  `;` and the greek question mark `;` have to go
- we need to have all the special characters that we use also enumerated
- `::` will probably be reserved for subdomains

These rules should be formalized at a later point.

**Comment by astrokov7** [comment]
Just reminder that the `@` character is reserved for `account@domain` constructs, `#` — for `asset#domain`, `$` — for `trigger$domain` and `%` — for `validator%account`.
