### ISSUE TITLE
Document current configuration update

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#257]
Currently, we often hear about a bug with this error message:

> Error: Failed to build `Configuration` from `ConfigurationProxy`

As far as I know, it was previously fixable by resetting the environment and picking a proper container for Iroha in Docker-compose (`dev` instead of `lts`).

```bash
git checkout iroha2-dev
# Backup your config here
git reset --hard
git pull
```

As an example, I'll copy a log provided by Vishal Mahajan running [this](https://hyperledger.github.io/iroha-2-docs/guide/build-and-install.html) part of the doc [today](https://t.me/hyperledgeriroha/26094):

```
Output: 
[+] Running 4/0
 ⠿ Container iroha-iroha2-1  Created                                       0.0s
 ⠿ Container iroha-iroha3-1  Created                                       0.0s
 ⠿ Container iroha-iroha0-1  Created                                       0.0s
 ⠿ Container iroha-iroha1-1  Created                                       0.0s
Attaching to iroha-iroha0-1, iroha-iroha1-1, iroha-iroha2-1, iroha-iroha3-1
iroha-iroha0-1  | Error: Failed to build Configuration from ConfigurationProxy
iroha-iroha0-1  | 
iroha-iroha0-1  | Caused by:
iroha-iroha0-1  |     Proxy failed at build stage due to: maximum_transactions_in_signature_buffer
iroha-iroha0-1  | 
iroha-iroha0-1  | Location:
iroha-iroha0-1  |     config/src/[iroha.rs:157](http://iroha.rs:157/):14
iroha-iroha1-1  | Error: Failed to build Configuration from ConfigurationProxy
iroha-iroha1-1  | 
iroha-iroha1-1  | Caused by:
iroha-iroha1-1  |     Proxy failed at build stage due to: maximum_transactions_in_signature_buffer
iroha-iroha1-1  | 
iroha-iroha1-1  | Location:
iroha-iroha1-1  |     config/src/[iroha.rs:157](http://iroha.rs:157/):14
iroha-iroha3-1  | Error: Failed to build Configuration from ConfigurationProxy
iroha-iroha3-1  | 
iroha-iroha3-1  | Caused by:
iroha-iroha3-1  |     Proxy failed at build stage due to: maximum_transactions_in_signature_buffer
iroha-iroha2-1  | Error: Failed to build Configuration from ConfigurationProxy
iroha-iroha3-1  | 
iroha-iroha2-1  | 
iroha-iroha2-1  | Caused by:
iroha-iroha2-1  |     Proxy failed at build stage due to: maximum_transactions_in_signature_buffer
iroha-iroha3-1  | Location:
iroha-iroha3-1  |     config/src/[iroha.rs:157](http://iroha.rs:157/):14
iroha-iroha2-1  | 
iroha-iroha2-1  | Location:
iroha-iroha2-1  |     config/src/[iroha.rs:157](http://iroha.rs:157/):14
iroha-iroha0-1 exited with code 1
iroha-iroha1-1 exited with code 1
iroha-iroha3-1 exited with code 1
iroha-iroha2-1 exited with code 1
```

The current fix is different: one should update the Docker-compose config or add an environment variable.
Example config change was shown by @appetrosyan (**please confirm** if the text is actual and belongs in `docker-compose.yml` or another file):

> Please add the missing environment variables to the config/compose file.

```json
"QUEUE": {
    "MAXIMUM_TRANSACTIONS_IN_BLOCK": 512,
    "MAXIMUM_TRANSACTIONS_IN_QUEUE": 65636,
    "MAXIMUM_TRANSACTIONS_IN_SIGNATURE_BUFFER": 65536,
    "TRANSACTION_TIME_TO_LIVE_MS": 86400000,
    "FUTURE_THRESHOLD_MS": 1000
}
```

**I need additional information.**

Specifically, how could each of the `QUEUE` configuration values be set?

* A part of `peer/config.json`?
* Environment variables in `docker-compose.yml` or bare-metal environment vars? And if so, each variable in the list above is set separately?

I know the last question specifically was asked in Hyperledger Iroha Community, but let's add more specific answers and examples so the doc can be reliably updated.

**Comment by outoftardis** [comment]
will be updated via configuration rfc

**Comment by 0x009922** [comment]
The configuration reference overhaul is tracked here: #392
