### ISSUE TITLE
Proposal: use `$` in `sh`-lang code blocks for commands

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha-2-docs#267]
Instead of:

```bash
docker-compose up
```

write:

```bash
$ docker-compose up
```

- it is visually easier to understand that the code snippet is a command for shell
- it does not affect "Copy to clipboard" button behaviour, i.e. `$` character is not copied. However, it still could be selected manually.

Preview:

<img width="684" alt="image" src="https://user-images.githubusercontent.com/43530070/221474310-0178b48f-1a72-40b3-ab97-4338bd87bf1f.png">

**Comment by appetrosyan** [comment]
I don't think that this is useful. The reason why some distribution wikis use the `$` sign is because some commands need to be run as root. None of the commands in our wiki should be run as root. 

As for commands, I think we should solve the separation of command and output at the template level and just add a visual separator between a command and its output.

**Comment by 0x009922** [comment]
@appetrosyan, btw, it is already used in the Bash guide: 
<img width="706" alt="image" src="https://user-images.githubusercontent.com/43530070/222321474-c9af4e12-b75c-46c6-9feb-5118340eaad2.png">

**Comment by 0x009922** [comment]
On the other hand, [Troubleshooting Installation Issues](https://hyperledger.github.io/iroha-2-docs/guide/troubleshooting/installation-issues.html) section doesn't use `$` and it looks confusing:

<img width="713" alt="image" src="https://user-images.githubusercontent.com/43530070/222362828-43554ab0-75cd-42bf-a7f7-14038d0001bd.png">

**Comment by outoftardis** [comment]
It is less confusing when `$` is present, so I propose we merge #268: it's a really small change, but it'll make the docs consistent.
I also think if we can later have templates for this as to not put the `$` manually, that'd be good.
