### ISSUE TITLE
JS: add an example of the store asset transfer between accounts

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#273]
This may be useful because it's basic, and there's also some [interest](https://discord.com/channels/905194001349627914/905205848547155968/1080187927801384968) in the Hyperledger Iroha community by `alvarengacarlos`.

Today, Almeida also [expressed an interest](https://discord.com/channels/905194001349627914/905205848547155968/1080509530712064000) in knowing the details, specifically for JS SDK:

> When transferring a Store Asset between accounts, what do I have to specify in the 'amount' property, since Store Assets are not "quantifiable"?

**Comment by 0x009922** [comment]
I am researching this topic, and it seems that Iroha 2 doesn't support tranferring `Store` assets:

https://github.com/hyperledger/iroha/blob/31f5b2c397390f7ed8b48a52893c825eaec3de1d/core/src/smartcontracts/isi/mod.rs#L425-L450

Only `U32`, `U128` and `Fixed` numeric values are supported so far.

**Comment by 6r1d** [comment]
We won't fix this now; instead, we'll address a similar approach at https://github.com/hyperledger/iroha/issues/3279
