### ISSUE TITLE
Document new permissions

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#281]
The exact list will be updated later, I'll discuss it in our chat, but this issue would help the community. In fact, there was a [question](https://t.me/hyperledgeriroha/26424) concerning the permissions from Yasir in the Hyperledger Iroha Community today:

> If we want to store profiles on blockchain like some ID, some names , addresses etc and can it also be permissioned that only allowed people can view it? In iroha1 we could set user account details for this but I am hoping that Iroha2 may have some better way for it?

**Comment by outoftardis** [comment]
closing, it is a part of #311
