### ISSUE TITLE
Change Java/Kotlin examples from text to linked code, refer to a demo repo

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#288]
Currently, the [Java tutorial](https://github.com/hyperledger/iroha-2-docs/blob/main/src/guide/kotlin-java.md) combines linked code snippets like `<<<@/snippets/InstructionsTest.kt#java_register_domain{kotlin}` with the code embedded in Markdown.

It'll be more productive to get rid of embedded code completely, specifically because of this section:

> Instead of providing the complete basics, we shall assume knowledge of the most widely used concepts, explain the unusual, and provide some instructions for creating your own Iroha 2-compatible client

Realistically, all we can expect with that approach is to confuse most Iroha 2 Java SDK users.

Ideally, we need to:

* link a repo with examples, which, I believe, we've got
* ensure that each example runs
* Ensure that pieces of code in the text are present in the said repo

**Comment by nxsaken** [comment]
Superseded by #304.
