### ISSUE TITLE
[suggestion] Update the documentation with the methods for deploying Iroha 2 on multiple servers #3319

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#294]
Moved to the tutorial from the original Iroha issue https://github.com/hyperledger/iroha/issues/3319 by @minghongxu.

----------

### Feature request

Official methods for deploying Iroha 2 on multiple servers

### Motivation

Hi everyone,

I attempted to deploy Iroha 2 on multiple servers (hosts) to emulate a scenario involving various companies in the blockchain community.
I initially tried to use Docker swarm but encountered several issues that proved too complex to resolve.
As a result, I started to research whether there were any official methods for deploying Iroha 2 on multiple servers. Unfortunately, I found no relevant information on the website, even though this is a common scenario many people may encounter.
I would be grateful if anyone could give me some suggestions.

Best regards to you!

**Comment by outoftardis** [comment]
This is a duplication of #293. I'll close this issue and leave the other one open.
.
