### ISSUE TITLE
Cosmetic changes: links and info block

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#299]
JS: add links

> To work with Torii, we need to know Iroha Torii URLs. Our Iroha Peer is configured to listen for API endpoints at http://127.0.0.1:8080 and for telemetry endpoints at http://127.0.0.1:8081

Add an INFO block here:

> Note that the keys in client configuration are given in multi-hash format. If you are experiencing issues parsing the keys in this format, check the troubleshooting section.

**Comment by outoftardis** [comment]
Closed in #300
