### ISSUE TITLE
Render diagrams using Mermaid

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha-2-docs#307]
## Description

There are some UML diagrams located in `src/guide/diagrams-src`. Those could be included in Markdown directly, instead of generating images manually and putting them into Markdown.

**Example for `asset.puml`:**

```mmd
classDiagram
    class Asset
    class AssetDefinition
    
    class Id {
        definition_id
        account_id
    }
    
    class Mintable {
        Infinitely
        Once
        Not
    }
    
    class AssetValue {
        Quantity
        BigQuantity
        Fixed
        Store
    }
    
    Asset -- AssetDefinition
    Asset -- Id
    AssetDefinition -- Mintable
    AssetDefinition -- AssetValue
    AssetDefinition -- Id
    
    Asset : id {Id}
    Asset : value
    
    AssetDefinition : id {Id}
    AssetDefinition : value_type {AssetValueType}
    AssetDefinition : mintable {Mintable}
    AssetDefinition : metadata
```

**GitHub-rendered diagram:**

```mermaid
classDiagram
    class Asset
    class AssetDefinition
    
    class Id {
        definition_id
        account_id
    }
    
    class Mintable {
        Infinitely
        Once
        Not
    }
    
    class AssetValue {
        Quantity
        BigQuantity
        Fixed
        Store
    }
    
    Asset -- AssetDefinition
    Asset -- Id
    AssetDefinition -- Mintable
    AssetDefinition -- AssetValue
    AssetDefinition -- Id
    
    Asset : id {Id}
    Asset : value
    
    AssetDefinition : id {Id}
    AssetDefinition : value_type {AssetValueType}
    AssetDefinition : mintable {Mintable}
    AssetDefinition : metadata
```

For detailed syntax documentation, examples, live editor etc please follow here: [Class diagrams | Mermaid](https://mermaid.js.org/syntax/classDiagram.html).

### Benefits

- No need to generate images manually, shortened feedback loop in development
- Diagrams are generated as SVGs, therefore:
  - it's scalable
  - it's theme-adoptable (dark/light)
  - text is copyable
  - the content is generally readable by e.g. crawlers, which might enhance SEO
  
### How-to

Set up Mermaid.js for VitePress: [Getting Started | VitePress Plugin Mermaid](https://emersonbottero.github.io/vitepress-plugin-mermaid/guide/getting-started.html)

**Comment by 6r1d** [comment]
> the content is generally readable by e.g. crawlers, which might enhance SEO

So it's not rendered on the fly, instead being pre-rendered to an SVG document? Nice!

**Comment by appetrosyan** [comment]
The less we render on the back-end the better.

**Comment by 0x009922** [comment]
> So it's not rendered on the fly, instead being pre-rendered to an SVG document? Nice!

> The less we render on the back-end the better.

It is rendered on **back-end** during the build stage (as everything else in markdown files). When static files are served to the browser (i.e. front-end), they already contain compiled SVGs.

It is rendered **on the fly** in a sense that you don't build intermediate artifacts and store them somewhere. You don't need to care about anything, just like when you write mermaid diagrams in GitHub.

**Comment by outoftardis** [comment]
I like this suggestion, I think this would be much better than what we have at this moment.
