### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha-2-docs#308]
Make sure that the documentation and its interpretation is up to date, with a review of what we have written so far. 

- [ ] Troubleshooting
- [ ] Install
- [ ] Config
- [ ] Genesis
- [ ] Rust SDK
- [ ] Bash usage
- [ ] Python usage
- [ ] Kotlin/Java
- [ ] JavaScript/TypeScript

**Comment by 6r1d** [comment]
Topics we've discussed:

**Account restructuring**
- [ ] Document everything updated by this change
- [ ] Check that all SDK docs are updated regarding this change

A detailed, working example of building something with blockchain.

Documenting the efficient use of Iroha 2: when to use `Store` assets and metadata (account information).

Java SDK readiness: Java doc needs to be very detailed, separating Java and Kotlin documents.

Explain how and why we do things in a certain way in Iroha 2. Given the integration of I2 in other projects, this will need further discussion.

Configuration and key management section: describe proper key storage, even if we use JSON for storing keys in our demos.

Document the use of block streaming API.

Explain the use of Kotlin contexts in its tutorial.

**Comment by 6r1d** [comment]
I think extending the query filtering documentation is also valid since it was discussed today with @Arjentix.
Let's add it to the to-do list.

**Comment by nxsaken** [comment]
Obsolete
