### ISSUE TITLE
Actualise JS tutorial according to `rc13`

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha-2-docs#313]
Part of #308.

**Comment by 0x009922** [comment]
It doesn't make sense to update JS tutorial to `rc14`, because we don't even know the exact hash commit of Iroha `rc14`. So, update the tutorial to the latest stable release (`rc13`).

**Comment by lutfi-haslab** [comment]
hi, do you have working ts example for registering asset?
i am using this code but have no luck. Using bash it is work fine.
```ts
(async () => {
  try {
    const time = AssetDefinition({
      value_type: AssetValueType("Quantity"),
      id: AssetDefinitionId({
        name: "peruri",
        domain_id: DomainId({ name: "hasdev" }),
      }),
      metadata: Metadata({ map: MapNameValue(new Map()) }),
      mintable: Mintable("Infinitely"), // If only we could mint more time.
    });

    const register = Instruction(
      "Register",
      RegisterBox({
        object: EvaluatesToRegistrableBox({
          expression: Expression(
            "Raw",
            Value("Identifiable", IdentifiableBox("AssetDefinition", time))
          ),
        }),
      })
    );

    const data = await client.submitExecutable(
      toriiRequirements,
      Executable("Instructions", VecInstruction([register]))
    );

    console.log(data);
  } catch (error) {
    console.log(error);
  }
})();
```

**Comment by 0x009922** [comment]
Hi @lutfi-haslab. What version of Iroha do you use? (please provide git revision commit if possible).

And please describe in a more detailed what do you mean by "have no luck": your script failed to execute? To send transaction? You got 400 error from Iroha? You have error message in Iroha logs?
