### ISSUE TITLE
Split the Value type to subtypes

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#321]
Mirrors https://github.com/hyperledger/iroha/issues/3418

It would address [this question](https://github.com/hyperledger/iroha-2-docs/pull/318#issuecomment-1517443224) and make Iroha's `Value` more logical.

`Value::Primitive::{Bool, String, (Hash), Numeric::{u32, u128, Fixed}}`
`Value::Metadata::{LimitedMetadata, MetadataLimits, TransactionLimits, LengthLimits, Ipv6Addr, Ipv4Addr}`

**Comment by outoftardis** [comment]
not implemented in the iroha yet

**Comment by nxsaken** [comment]
Obsolete, see https://github.com/hyperledger/iroha/pull/4305.
