### ISSUE TITLE
Quick Start with Docker instructions in Iroha 2 require updates for new `docker-compose` files in `dev` branch

### ISSUE THREAD

**Issue by AlexStroke** [hyperledger/iroha-2-docs#329]
### Description:
The Quick Start with Docker instructions in the Iroha 2 documentation no longer work without additional modifications to the docker-compose file names in `dev` branch, as the default `docker-compose.yml` file is no longer available. Instead, there are multiple docker-compose files to choose from:
- `docker-compose-local.yml`
- `docker-compose-lts.single.yml`
- `docker-compose-stable.single.yml`
- `docker-compose.dev.yml`
- `docker-compose.dev.single.yml`
- `docker-compose.lts.yml`
- `docker-compose.stable.yml`

This change requires an update to the Quick Start with Docker instructions to reflect the new available docker-compose files and the necessary adjustments for using them.

### Steps to Reproduce:

1. Follow the [Quick Start with Docker](https://hyperledger.github.io/iroha-2-docs/guide/quick-start.html) instructions in the Iroha 2 `dev` branch documentation 
2. Observe that the docker-compose.yml file is not available, and there are multiple docker-compose files to choose from
3. Attempt to run docker-compose up as described in the instructions

### Actual Results:
The Quick Start with Docker instructions do not work, as they reference a non-existent docker-compose.yml file. Users must manually select and adjust the docker-compose file name to proceed.

### Expected Results:
The Quick Start with Docker instructions should be updated to include the necessary modifications to the docker-compose file names, providing clear guidance on which file to use and any necessary adjustments. This will allow users to successfully follow the instructions and quickly start using Iroha 2 with Docker.

**Comment by 6r1d** [comment]
Thanks, I will address that.
