### ISSUE TITLE
Blockchain storage architecture and metadata

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#334]
After yesterday's community discussion and https://github.com/hyperledger/iroha-2-docs/pull/318, I am trying to understand how Metadata implementation is stored in Kura, compared to `Store` assets.

Does each change in metadata create some record in the blockchain with an update, making the read performance similar and reducing it in cases of large Metadata contents?

The approach to performance here is worth documenting to explain to the users when `Store` assets are preferable, at least in my opinion.

**Comment by 6r1d** [comment]
As confirmed by @appetrosyan, both `Store` and `metadata` modifications are stored as blockchain records, thus the retrieval speed is only worse for metadata in certain cases.

**Comment by nxsaken** [comment]
Contained in #450 and #451.
