### ISSUE TITLE
[documentation] Practical documentation on metadata and store assets

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#337]
A copy of https://github.com/hyperledger/iroha/issues/3456 by @v-a-net

------

### Documentation URL(s)

https://hyperledger.github.io/iroha-2-docs/guide/configure/metadata-and-store-assets.html
https://hyperledger.github.io/iroha-2-docs/guide/blockchain/metadata.html

### Description

Iroha 1 provides an easy way to store metadata in user account. This feature was super useful to use Iroha as a data ledger rather than just using fungible assets.

Iroha 2 seems to keep this super feature and even extends it with metadata and store assets (https://hyperledger.github.io/iroha-2-docs/guide/configure/metadata-and-store-assets.html).

### Your suggestions

Could you provide a more detailed documentation (especially client usage in rust and with the bash client if it's implemented yet) about how practically using metadata and store assets for iroha 2 ?

**Comment by 6r1d** [comment]
> This feature was super useful for using Iroha as a data ledger rather than just using fungible assets.

Well, let's imagine its internal behaviour. Both `Store` and `metadata` would have separate records in the blockchain for every update. Given that, you can only get more fields than you need with Metadata.

In that case, does it mean only a question of API usability remains here?

**Comment by v-a-net** [comment]
I think so! From my understanding of the current implementation, I think that the tutorial documentation mainly lacks practical details and examples about this topic. This was the main reason of this issue.

**Comment by nxsaken** [comment]
Superseded by #450 and #451.
