### ISSUE TITLE
Full example of creating account with signatory. 

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha-2-docs#343]
Rough draft is 

if you want an empty signatory, 
```rust
let create_account = Account::new("alice@wonderland".parse().unwrap(), []);
```

If you want to add a signatory, you prepare one from a single public key:
```rust
let pub_key = PublicKey::from_str("ed01207233BFC89DCBD68C19FDE6CE6158225298EC1131B6A130D1AEB454C1AB5183C1").unwrap();
let account = Account::new("alice@wonderland".parse().unwrap(), [pub_key]);#
```
Keep in mind that under the new account schema the signatory will be a mandatory field, so you will need to produce a new key

**Comment by sleep-all-dae** [comment]
```
let _longhand_account_id = account_id_struct {
            name: name.parse().expect("Unable to parse Name"),
            domain_id: domain_id.parse().expect("Unable to parse domain id"),
        };

        let _id: AccountId = account_id
            .parse::<account_id_struct>()
            .expect("Unable to parse account id");

        let pub_key = PublicKey::from_str(
            "ed01207233BFC89DCBD68C19FDE6CE6158225298EC1131B6A130D1AEB454C1AB5183C1",
        )
        .unwrap();
      
       ##################################### Getting two errors
       // error: the trait bound `RegistrableBox: std::convert::From<IdentifiableBox>` is not satisfied
       //label: required by a bound introduced by this call

       //error: the trait bound `RegistrableBox: std::convert::From<IdentifiableBox>` is not satisfied
       //label: the trait `std::convert::From<IdentifiableBox>` is not implemented for `RegistrableBox`

        let _create_account = RegisterBox::new(IdentifiableBox::from(Account::new(_id, [pub_key])));
}
```

Hi, I am getting this above error even after I followed official documentation and the above example

**Comment by sleep-all-dae** [comment]
`
pub mod services_methods {

    use iroha_crypto::PublicKey;
    use iroha_data_model::{
        account::{Account, Id as account_id_struct},
        prelude::{AccountId, Domain, DomainId, Instruction, RegisterBox},
        IdentifiableBox,
    };

    pub fn create_new_account(account_id: String, domain_id: String, name: String) {
        let _longhand_account_id = account_id_struct {
            name: name.parse().expect("Unable to parse Name"),
            domain_id: domain_id.parse().expect("Unable to parse domain id"),
        };

        let _id: AccountId = account_id
            .parse::<AccountId>()
            .expect("Unable to parse account id");

        let pub_key = PublicKey::from_str(
            "ed01207233BFC89DCBD68C19FDE6CE6158225298EC1131B6A130D1AEB454C1AB5183C1",
        )
        .unwrap();

        let _create_account = RegisterBox::new(IdentifiableBox::from(Account::new(_id, [pub_key])));
    }
}
`

above is the entire module.
