### ISSUE TITLE
[suggestion]  Asset Burn on Iroha2 client cli 

### ISSUE THREAD

**Issue by rezacute** [hyperledger/iroha-2-docs#350]
### Feature request

I would like Iroha 2 cli i\has `burn` asset functionality

### Motivation

burn feature is essential.

**Comment by appetrosyan** [comment]
Functionality is there.

**Comment by rezacute** [comment]
which branch? there is no burn option on stable branch

**Comment by Erigara** [comment]
i've checked this on latest `iroha2-dev` branch

**Comment by outoftardis** [comment]
the functionality is in the stable branch as well (https://github.com/hyperledger/iroha/blob/iroha2-stable/client_cli/src/main.rs#L653)
