### ISSUE TITLE
addition to the documentation Java/KotlinSDKs

### ISSUE THREAD

**Issue by timofeevmd** [hyperledger/iroha-2-docs#364]
After a conversation with Marin and Viktor, it was decided to create a new project with snippets for JavaSDK and KotlinSDK, since it is necessary to implement additional classes containing additional functionality

The documentation contains actual snippets for KotlinSDK
For JavaSDK, implementation of tests covering the following functionality

 - [ ] 1. Iroha 2 Client Setup
 - [ ] 2. Configuring Iroha 2
 - [ ] 3. Querying and Registering Domains
 - [ ] 3.1. imports
 - [ ] 3.2. send query (for check)
 - [ ] 3.3. send transaction (for create)
 - [ ] 4. Registering an Account
 - [ ] 4.1 there is no information on obtaining a public key
 - [ ] 4.2. send query (for check) or a mention of the possibility of sending a request with a link to previous examples
 - [ ] 5. Registering and minting assets
 - [ ] 5.1. example mypy annotations
 - [ ] 5.2. send query (for check) or a mention of the possibility of sending a request with a link to previous examples
 - [ ] 6. Transferring assets
 - [ ] 6.2. send query (for check) or a mention of the possibility of sending a request with a link to previous examples
 - [ ] 7. Burning assets
 - [ ] 7.2. send query (for check) or a mention of the possibility of sending a request with a link to previous examples
 - [ ] 8. Visualizing outputs
 
snippets must also be implemented through links to the code under test in the repository

**Comment by outoftardis** [comment]
migrate this into the new repository for examples
