### ISSUE TITLE
Group asset transfer

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#369]
I need to add a group asset transfer example for each API. Currently, the Rust example is available in the Core chat (a transfer from Bob to Alice):

```rust
let transfer_a = TransferBox::new(
    IdBox::AssetId(AssetId::new(asset_definition_id_a, bob_id)),
    quantity.to_value(),
    IdBox::AccountId(alice_id.clone()),
);
let transfer_b = TransferBox::new(
    IdBox::AssetId(AssetId::new(asset_definition_id_b, bob_id)),
    quantity.to_value(),
    IdBox::AccountId(alice_id.clone()),
);

let metadata = UnlimitedMetadata::default();
let instructions: Vec<Instruction> = vec![transfer_a.into(), transfer_b.into()];
let tx = iroha_client
    .build_transaction(instructions, metadata)
    .wrap_err("Error building a group transfer transaction")?;
```

Other things to mention:

* There is no single instruction to transfer a group of assets.
* The user will need to send a transaction, which contains multiple transfer instructions.
* These instructions will be applied either together or not at all.

**Comment by outoftardis** [comment]
this should be addressed with the introduction of the Cookbook, I've added a placeholder topic for this example
