### ISSUE TITLE
Minting a signature check condition

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#370]
https://github.com/hyperledger/iroha-python/issues/155 should be added to doctests from Python and propagated to the other documentation parts. It was already requested in the community.

**Comment by outoftardis** [comment]
this might change in the future, so postpone for now

**Comment by 0x009922** [comment]
Specifically, it might change because of this:

- https://github.com/hyperledger/iroha/issues/3526
  - https://github.com/hyperledger/iroha/pull/3869

**Comment by nxsaken** [comment]
@0x009922 is this relevant?
