### ISSUE TITLE
Make the documenting of the Rust toolchain selection a part of the release process

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#378]
I don't think much needs to be done, but we should document a recommended version and how to install it with Rustup.

The Validator feature in Kagami required to use of the fresh toolchain, add `rust-src` and `WASM` target support:

```
rustup default nightly-2023-06-25
rustup component add rust-src --toolchain nightly-2023-06-25
rustup target add wasm32-unknown-unknown --toolchain nightly-2023-06-25
```

@appetrosyan, what is your opinion here?

**Comment by outoftardis** [comment]
we recommend the latest version
