### ISSUE TITLE
Update WASM guide

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha-2-docs#39]
Update the Web-assembly guide to include changes made in [#2164](https://github.com/hyperledger/iroha/pull/2164)

**Comment by outoftardis** [comment]
@appetrosyan the mentioned PR was closed before merging, is this task still applicable?

**Comment by appetrosyan** [comment]
Yes, the work in question was merged as part of  https://github.com/hyperledger/iroha/pull/2314,
