### ISSUE TITLE
Partial example snippets vs. full examples

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#398]
I and @0x009922 have two different ideas for future code documentation, and the difference here is quite significant.

I'll start with my approach: extend the documentation generation to use several code regions in a single block through the concatenation. Typically, we have the dependencies and several tests in a piece of the code, which I must write in separate blocks. Connecting blocks in Markdown seems useful because we can build something out of the repeating parts. My approach also has a disadvantage: it's possible to overuse it and show the code not working because the dependencies belong to one file and the code belongs to another. My approach will look the same as the current documentation code examples, sometimes shorter.

Dmitry's approach is to have a single file for each test: despite the `main` function's overhead and test wrapper overhead, it shows the person starting to use Iroha the entire code, which tells them more about how to build their client code. He points out that the "Rust by example" book follows this approach (for instance, [this page](https://doc.rust-lang.org/rust-by-example/types/cast.html)), and this looks reasonable to me. He also points out the code in "Rust by example" has a lot of comments.

@mversic, @appetrosyan, we'd like your opinion on the matter.

**Comment by appetrosyan** [comment]
I vote for the smaller approach. If they are clearly delineated then the overhead is only paid during the `cargo check`.
