### ISSUE TITLE
Establish the version that is being documented

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#401]
As far as I understand, we document the latest `stable` and `lts` versions.

The Rust tutorial [documents](https://hyperledger.github.io/iroha-2-docs/guide/rust.html#_1-iroha-2-client-setup) is a different version, currently, it is `2.0.0-pre-rc.13`. We've discussed this topic with @mversic today and agreed on documenting the latest `stable` and `LTS`.

Moreover, we'd need to have a way to switch between the two. Code tabs would suffice here for starters, but potentially, we may need several versions of the tutorial as on ReadTheDocs.

I'm simply updating `Cargo.toml` to `=2.0.0-pre-rc.20`.
How do I pick the latest releases for LTS and stable?
Do I use GitHub or crates.io?

**Comment by appetrosyan** [comment]
It was always the policy to document only the `lts` and the latest `stable`. 

The latest `stable` as of now is `2.0.0-pre-rc.19`. However, it's not compatible with all of the SDKs yet. So it makes sense to wait a bit. 

However, I'd make sure that the release cadence no longer has major problems, in the sense that the releases are not post-poned.
