### ISSUE TITLE
Payment processing (FAQ or demo?)

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#427]
Previously, there was a community request by Ridwanulah Tijjani regarding the payment processing.

> Is it possible to use web 2 payments card like visa or master in iroha?

I think it's worth it to explain the way from the Iroha to the payment processing.
It may be explained either through FAQ section or a demo.
What are your opinions?

**Comment by outoftardis** [comment]
I'd suggest documenting payment processing, that should be enough. Do you think a demo is necessary?

**Comment by 6r1d** [comment]
> Do you think a demo is necessary?

No, I put it as only an example that was raised in the conversations before
