### ISSUE TITLE
Update the way of choosing the versions

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#432]
https://hyperledger.github.io/iroha-2-docs/guide/install.html#choose-version

* add a compatibility matrix here
* change the compatibility matrix to reflect `lts` and `stable`
* table should potentially reflect Iroha versions as well

@Mingela @dmitrivenger I'd like to see your comments

**Comment by Mingela** [comment]
Outlined there https://github.com/hyperledger/iroha-rfcs/pull/10#issuecomment-1814974203

As for `lts` and `stable` - true for now, after 2.0 release those most likely will change

**Comment by outoftardis** [comment]
compatibility matrix was added some time ago, closing this
