### ISSUE TITLE
Explain the Mint Genesis configuration syntax

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#440]
Recently, Matías Salimbene [asked us](https://t.me/hyperledgeriroha/30423) about the role of `object` field in Genesis `Mint` ISI.

Object here means we can mint both values and public keys, according to @Erigara.

```json
{
  "Mint": {
    "object": "44_u32",
    "destination_id": {
      "AssetId": "cabbage#garden_of_live_flowers#alice@wonderland"
    }
  }
}
```

**Comment by Erigara** [comment]
@6r1d 

Also `SignatureCheckCondition` ;)

And... increasing number of trigger repetitions.

```json
      {
        "Mint": {
          "object": 5,
          "destination_id": {
            "TriggerId": "my_cool_trigger"
          }
        }
      }
```

**Comment by Erigara** [comment]
It's kinda confusing to represent all this different actions by the same isi type.

**Comment by 6r1d** [comment]
> Also SignatureCheckCondition ;)

Can you elaborate, please?

> And... increasing number of trigger repetitions.

Does it mean such Mint instance will increment `my_cool_trigger` repetitions by five?

> It's kinda confusing to represent all this different actions by the same isi type.

If there's no technical limitation over how the instruction is represented, I'm sure `Mint` configuration could be improved.
Then again, I wonder whether we want to support the old way of configuring it.

**Comment by Erigara** [comment]
> Does it mean such Mint instance will increment my_cool_trigger repetitions by five?

Yes.

> Can you elaborate, please?

Sure.

Mint instruction could be used to change how user transaction's signatures are checked (either any account signature to be attached or all signatures to be attached).

```json
{
  "Mint": {
    "object": { "SignatureCheckCondition": {"AnyAccountSignatureOr": []} },
    "destination_id": {
      "AccountId": "alice@wonderland"
    }
  }
}
```
