### ISSUE TITLE
Registering a new Peer to an Iroha Network

### ISSUE THREAD

**Issue by matisalimbene** [hyperledger/iroha-2-docs#447]
The documentation to register a new peer states:

`After your peer is running, you should submit the register peer instruction. The peer will go through the handshake process and start chatting with the network.`

So: 
1- Start new peer
2- Issue register command to register peer in the network

But, for the new peer to run, It needs to be provided with a genesis configuration. ¿Do I need to start the new peer with the genesis configuration of my already running Iroha network?

¿Does this mean that for each new peer I want to register, I need to provide a list of all the current members of the network?

**Comment by mversic** [comment]
seems that atm, whatever you used as the `TRUSTED_PEERS` when starting the network is what you should use on your new peer

**Comment by matisalimbene** [comment]
@mversic It seems to work that way. But for instance, after I register the new peer, If I query the peer count using http://localhost:8081/status/peers I get odd results:

http://localhost:8080/status/peers return 4
http://localhost:8081/status/peers return 4
http://localhost:8082/status/peers return 4
http://localhost:8083/status/peers return 3
http://localhost:8084/status/peers return 3

They should return 5 right? the initial 4, plus the one I'm registering.

**Comment by mversic** [comment]
they should all return `4`. `status/peers` returns the number of connected peers excluding the reporting peer

**Comment by mversic** [comment]
there is a bug, I'm working on it

**Comment by mversic** [comment]
the fix will be ready today

**Comment by matisalimbene** [comment]
@mversic Thanks Marin. This is on the `iroha-stable` branch, correct? That's the branch I'd need to rebuild to have these fixes appled.

**Comment by mversic** [comment]
The fix hasn't been merged yet

**Comment by mversic** [comment]
> @mversic Thanks Marin. This is on the `iroha-stable` branch, correct? That's the branch I'd need to rebuild to have these fixes appled.

the fix was merged. Yes you can use `iroha2-stable` branch or pull the latest `iroha2-stable` docker image
