### ISSUE TITLE
Make sure the code for CanMintAssetsWithDefinition and CanRegisterAssetsWithDefinition is shown

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#462]
Quoting https://github.com/hyperledger/iroha-2-docs/issues/460,

> According to @mversic [here](https://t.me/hyperledgeriroha/30724),

> > there is no such thing as CanMintUserAssetDefinitions. You cannot mint asset definitions, but you can mint assets

> We may need to update the example code further

Then, according to @mversic [here](https://t.me/hyperledgeriroha/30739),

> you are correct, `CanMintUserAssetDefinitions` was renamed to `CanMintAssetsWithDefinition`

We need to ensure the API and examples stay consistent with the codebase in this regard.

**Comment by Stukalov-A-M** [comment]
Example updated https://github.com/hyperledger/iroha-2-docs/pull/467
