### ISSUE TITLE
Update Branch Names in Tutorial

### ISSUE THREAD

**Issue by AlexStroke** [hyperledger/iroha-2-docs#486]
### Description

Since Iroha's branching model changed in https://github.com/hyperledger/iroha/issues/4433, the entire documentation needs to be updated as follows:
- Replace all instances of `iroha2-dev` with `main`.
- Replace all instances of `iroha2-stable` with `stable`.
- Remove all instances of `iroha2-lts` as we have discontinued this branch.

### Example
![image](https://github.com/hyperledger/iroha-2-docs/assets/111361420/e23450ab-6bf2-4927-b4d0-8081b188d36f)

**Comment by a-zorina** [comment]
edits added to [PR #504](https://github.com/hyperledger/iroha-2-docs/pull/504)
