### ISSUE TITLE
Pin issues to specific Iroha versions

### ISSUE THREAD

**Issue by nxsaken** [hyperledger/iroha-2-docs#489]
Currently, it's unclear which version of Iroha is targeted by an issue. This may cause (and have caused) the issue's Definition of Done to change on a new release – especially since Iroha is evolving quicker than the documentation can keep up.

To remedy this, we should be more specific about what Iroha version should be used as the source of truth. This way, even if a release happens, the goalpost for the issue stays the same. A separate issue targeting the new version can be opened instead, if needed. This will also help us support multiple versions of the documentation.

**Comment by mversic** [comment]
the person who opens the issue, should write how to reproduce it. This means to write the version of iroha which was used

**Comment by Mingela** [comment]
We could have a quick sorting with introducing major version labels (e.g. `LTS` and `stable` as of now)

**Comment by outoftardis** [comment]
we have done this, we have labels now, I don't think this issues should remain open
