### ISSUE TITLE
Incorrect Commands for Iroha Client CLI in Documentation

### ISSUE THREAD

**Issue by AlexStroke** [hyperledger/iroha-2-docs#498]
**Description:**
The current documentation instructs users to build the Iroha client using the following command:
```bash
cargo build -p iroha_client_cli --release
```
The correct command to build the Iroha client is:
```bash
cargo build --bin iroha
```
The artifacts will then be found in the `target/debug` directory.

**Suggested Fix:**
Update the documentation to use the correct build command:
```bash
cargo build --bin iroha
```
And specify that the artifacts will be in the `target/debug` directory.
As well replace all places with `iroha_client_cli` on `iroha`.

**Comment by 0x009922** [comment]
Related: #480
