### ISSUE TITLE
Account registration: a tool to generate internal ed25519 keys

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#82]
The "[account registration](https://hyperledger.github.io/iroha-2-docs/guide/bash.html#_4-registering-an-account)" part of the manual contains a constant public key: `ed0120a753146e75b910ae5e2994dc8adea9e7d87e5d53024cfa310ce992f17106f92c`.
The source and the generation method of that key would need to be recorded in the documentation.

**Comment by appetrosyan** [comment]
![image](https://user-images.githubusercontent.com/15856657/180751265-5c625937-5354-4f61-b55a-c52276e17762.png)

**Comment by outoftardis** [comment]
@6r1d does #92 close this issue?

**Comment by 6r1d** [comment]
Yes, thanks, closing this issue.
