### ISSUE TITLE
Document the FFI bindgen behaviour

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha-2-docs#83]
With the merge of https://github.com/hyperledger/iroha/pull/2314 we've added a complex infrastructure of FFI bindgen, that needs to be followed closely. @mversic has created an excellent graphic that should be included in our tutorials if possible. 

TikZ or SVG fine. Prefer TikZ. 

![image](https://user-images.githubusercontent.com/15856657/180741781-ab701928-0697-40fd-90d0-2e5e90b31015.png)

**Comment by outoftardis** [comment]
@6r1d transferred this to tex format, and I'm adding both the source and the output to the docs
