### ISSUE TITLE
Expand section on query behaviour

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha-2-docs#86]
@Mingela Identified a potential misbehaviour in pagination, and also requested that we document the filtering and sorting behaviour in-detail. 

We should create an advanced topic (or subsection in the existing queries), that explains how to create the required `QueryBox` object from the SDK, and how it's interpreted. 

We should document the sorting behaviour (the fact that there isn't any), and give a couple of examples of 
- [ ] Query that returns a single object, and a filter that matches on that object so we get one value returned,  
- [ ] Query that returns a collection of objects, half of which are filtered and the remaining half is paginated. 
- [ ] Query that filters (`Block`s) by  timestamp. 
- [ ] Query that returns a collection of objects none of which are matched by the filter and nothing is returned. 
- [ ] Proof of _idempotency_ (no WSV modifications => same query results). 
- [ ] Passthrough filter (all values are returned as is)
- [ ] Query that filters by block height.

**Comment by Mingela** [comment]
I'd add others for completeness:

- Query that filters `Block` by height (or range of values) (if possible).
- Query that returns a collection of objects all of which are matched by the filter and all are returned (trivial `true` filter).
- Idempotency verification. Having the same WSV and the query a response is always the same.
- Example of changing the WSV with introducing/changing an entity and it's appearance in a page.
