### ISSUE TITLE
Add versioning support 

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha-2-docs#89]
We need to support three versions of Iroha simultaneously: 
- Iroha2
- Iroha2-dev
- Iroha2-lts

We need to annotate features only present in `dev` and deprecated since `lts`. 

### Proposed solution

Have a custom vitepress environment e.g. 
``` 
::: Dev-only

```

for features which are only available in Dev. Another environment for deprecated features (e.g. `avaialable in LTS only`) and one for difference in behaviour e.g.
```
::: Diff LTS Dev

In LTS this does X, 

But on `iroha2-dev` it does Y. 
:::
```

**Comment by 6r1d** [comment]
I can think of these options right now:

* [Subdomains / directories](https://github.com/vuejs/vitepress/issues/109#issuecomment-1145781906)
* A custom, or possibly, an [existing component](https://github.com/fabioaanthony/markdown-it-vuepress-code-snippet-enhanced) to include code / text
* A custom component to integrate in the docs and show the commands for a given version in the tabs (but that doesn't deal with the documentation text)

**Comment by outoftardis** [comment]
@6r1d which version is going to be the default one? LTS? stable?
