### ISSUE TITLE
Metadata for an Asset definition

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#95]
We'll have to update an asset definition example with metadata that is currently possible to add.

Current example:

```python
import iroha2.data_model.asset as asset

time = asset.Definition(
    value_type=asset.ValueType.Quantity,
    id=asset.DefinitionId(name="time", domain_name="looking_glass"),
    # Here
    metadata={},
    mintable=False
)
```

According to @QuentinI, the proper keys for metadata have to be the Values and defined like that:

```python
from iroha2.sys.iroha_data_model import Value

time = asset.Definition(
    value_type=asset.ValueType.Quantity,
    id=asset.DefinitionId(name="time", domain_name="looking_glass"),
    # Here
    metadata={"a": Value.U32(10)},
    mintable=False
)
```

This [seems to work properly](https://t.me/hyperledgeriroha/23969), judging by the Hyperledger Iroha Community Telegram.

I believe we'll need to discuss what `Value` types might be there, how those are used and add proper examples.

**Comment by 6r1d** [comment]
Initial Hyperledger Iroha Community question is located [here](https://t.me/hyperledgeriroha/23960).

**Comment by outoftardis** [comment]
https://github.com/hyperledger/iroha-2-docs/pull/104 fixes the example. 

> I believe we'll need to discuss what Value types might be there, how those are used and add proper examples.
There was a line that said that metadata is outside the scope of the tutorial, so for me it seems as a "nice-to-have". I'd close this issue (bc the example is fixed), and then open a new one (e.g. "Add a topic discussing metadata") marking it as an enhancement
