### ISSUE TITLE
Metadata for an Account definition

### ISSUE THREAD

**Issue by 6r1d** [hyperledger/iroha-2-docs#98]
There's a [question](https://t.me/hyperledgeriroha/23997) in Hyperledger Iroha Community Telegram:

> Does Iroha2 have something similar to `SetAccountDetail` or `GetAccountDetail`?

According to @appetrosyan, we have `API` in Iroha 2 allowing to do this; accounts are the objects in the Blockchain, and each such object is allowed to contain metadata. Those objects work like `key`-`value` stores with values supporting each variant of the `Value` enum: numbers, strings, etc.

Assets may be transferred one-by-one, or in bulk using a `WASM` transaction.

Moreover, there's an asset called `Store`, specifically designed to be a package of data. It is designed for the situations when you don’t really need an asset, but instead a storage of `key`-`value` pairs.

**UPD**: according to @Arjentix, [there are](https://hyperledger.github.io/iroha-2-docs/guide/advanced/isi.html#setkeyvalue-removekeyvalue) `SetKeyValue` and `RemoveKeyValue` Iroha Special Instructions.
One can also get the key value using `FindAccountKeyValueByIdAndKey` Iroha Query.
It doesn't close the issue completely, we'll need to provide the examples, but it explains some aspects.

We'll need to document the details for those `API` features in each supported `SDK`.

**Comment by 6r1d** [comment]
Test link in Telegram: https://t.me/hyperledgeriroha/24016

**Comment by outoftardis** [comment]
I'll close this issue as the lack of info in our docs was addressed in #139 

> We'll need to document the details for those API features in each supported SDK.

I agree that we need to have examples for each supported language, I'll open a separate issue to track this (#152)
